### ISSUE TITLE
Question - samples view PCA plot

### ISSUE THREAD

**Issue by tamuanand** [federicomarini/pcaExplorer_serveredition#3]
Hi @federicomarini 

A question: Is the PCA computed on the raw counts or normalized counts?

Nice to have and Feature request (depending on your time) - when the user selects "raw counts" in the counts table tab, the PCA can be on the raw counts and when user selects "normalized counts", the PCA can be on the normalized counts.

Thanks

**Comment by federicomarini** [comment]
The PCA is computed always on a transformed version of the normalized counts.
The reason for that is explained very nicely also in the DESeq2 vignette - http://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html#data-transformations-and-visualization
In brief, it would be potentially very misleading to compute it on highly heteroscedastic data as the raw counts would be. Basically it would hide completely the contribution of many variable genes behind the ones that are highly expressed (as the variance would increase with the mean) - and you want something that stabilizes that trend, therefore the use of either `vst` or `rlog` transformations.

**Comment by tamuanand** [comment]
Thanks @federicomarini 

Suggestion - would it be possible to explicitly have that text somewhere in the instructions or vignette that the PCA plots are based on the normalized counts.

In my analyses for my clients, I typically provide the raw count PCA and the normalized count PCA just for the sake -  with the note that the users should only pay credence to the normalized counts PCA

Thanks again for the quick responses on many of my questions via GitHub

**Comment by federicomarini** [comment]
> would it be possible to explicitly have that text somewhere in the instructions or vignette that the PCA plots are based on the normalized counts.

The function for running the PCA is actually expecting a DESeqTransform object, so that would likely fail on a non-transformed set.
This information is already present in the vignette and in the documentation, I will have to think of a placement for this info, as long as it does not overcrowd the ui (which, as you might have seen, is a tricky task!)

> In my analyses for my clients, I typically provide the raw count PCA and the normalized count PCA just for the sake - with the note that the users should only pay credence to the normalized counts PCA

If you are using normalized counts, you can get pretty chaotic and potentially misleading insights out of the data.
The PCA algorithm expects data that to some degree should be homoscedastic, and as you can see from the vignettes of DESeq2, the normalized counts are not really suitable to be provided as input. 
Just my 2 cents, but I would leave in the PCA done on transformed values only.
